#define TCP_PORT 8080
#define DEBUG_printf printf
#define BUF_SIZE 2048
#define POLL_TIME_S 5
#define SYNC_PIN 16
#define DATA_PIN 17
#define PIO_INSTANCE pio0
#define DATA_SM 0 
#define SYNC_SM 1 

#define DMA_CHANNEL 0
#define DMA_CHANNEL_MASK (1u << DMA_CHANNEL)
#define DMA_DATA_SIZE 32

#define BUFF_WIDTH 768
#define HALF_BUFF_HEIGHT 312
#define FULL_BUFF_HEIGHT HALF_BUFF_HEIGHT * 2


#define HALF_BUFFER_SIZE BUFF_WIDTH * HALF_BUFF_HEIGHT / DMA_DATA_SIZE
#define FULL_BUFFER_SIZE BUFF_WIDTH * FULL_BUFF_HEIGHT / DMA_DATA_SIZE
#define DATA_COUNT_PER_ROW BUFF_WIDTH / DMA_DATA_SIZE